### ISSUE TITLE
`assertModuleGraph` doesn't take into account baselined `restricted` violations through `allowed`

### ISSUE THREAD

**Issue by saifc** [jraska/modules-graph-assert#172] opened 2022-04-20 15:56 UTC
`assertModuleGraph` doesn't take into account allowing specific violations as an exception to a broader `restricted` rule.
For example, trying to allow `:services:dialogs` to depend on `libraries:shared-prefs:impl` through the rules below fails with the following message
```
Execution failed for task ':assertRestrictions'.
> Dependency '':services:dialogs' -> ':libraries:shared-prefs:impl' violates: ':services:\S* -X> :libraries:[a-zA-Z0-9:\-]*:impl'
```
_Rules:_
```
restricted = arrayOf(":services:\\S* -X> :libraries:[a-zA-Z0-9:\\-]*:impl")
allowed = arrayOf(":services:dialogs -> :libraries:shared-prefs:impl")
```

**Comment by jraska** [comment] 2022-08-17 14:49
Hi, sorry for late response - missed the notifications 😞 

Thanks for raising an issues and using the plugin 👍 @saifc @johnLegasse 

### This is expected behaviour

The restricted/allowed checks are completely independent from each other - therefore what you are experiencing now is a feature by design :)

It was a design choice when [discussing API for version 2.0](https://github.com/jraska/modules-graph-assert/issues/129#issuecomment-954581268) with conclusion of these checks to be independent. 

The reasoning behind that is that it brings a circular problem - is allowed what is restricted or is restricted what is allowed - which one wins?
Therefore the checks are treated independently and they don't know about each other on purpose
- If some `restricted` rule finds match - assertions fails regardless `allowed`
- If some module dependency does not match the `allowed` rules - assertion fails 

Talking about the cases above in next messages ...

**Comment by jraska** [comment] 2022-08-17 14:49
> Rules:
> 
> restricted = arrayOf(":services:\\S* -X> :libraries:[a-zA-Z0-9:\\-]*:impl")
> allowed = arrayOf(":services:dialogs -> :libraries:shared-prefs:impl")

@saifc - I would remove the `restricted` completely and stick only to allowed + add your other allowed rules - what is not allowed is restricted by the `allowed` rules.

**Comment by jraska** [comment] 2022-08-28 09:27
Hey, I will close the issue for now - please if there is more to follow up, reopen it. 

Thanks

**Closed by jraska** 2022-08-28 09:27 UTC
