### ISSUE TITLE
Generating module graph for single module

### ISSUE THREAD

**Issue by ILikeYourHat** [jraska/modules-graph-assert#50] opened 2020-05-11 13:56 UTC
Hi 🙂 
I have a problem generating module graph for my project, using `generateModulesGraphvizText` command.

Expected outcome:
 - I want to see the whole module tree, starting from `:app` module. This tree, and only this tree.

My first approach: just `./gradlew generateModulesGraphvizText`. Ok, it works for `:app` module, but it also prints tree for any other module with this plugin. This is not what I want.

My second approach: `./gradlew generateModulesGraphvizText -Pmodules.graph.of.module=:app`. This cause an error: `Key :app is missing in the map.` 😢 

My third approach: `./gradlew app:generateModulesGraphvizText`. This works partially as expected, but shows only direct dependencies. So if we have `:app <- :b <- :c`, only `:app <- :b` will be printed, and `:b -> :c` will not. This is also not what I want.

Is there a way to achieve what I want? You can reproduce those behaviors in your example project.

**Comment by jraska** [comment] 2020-05-11 20:45
Hi, the third approach should do what you want. If there is an `:app <- :b <- :c` then also `:b -> :c` will be in a graph.

By running `./gradlew app:generateModulesGraphvizText` in the example project I got this, which I believe is what you want? Therefore the problem has to be elsewhere? 

```
digraph G {
":app" -> ":feature-one" [color=red style=bold]
":app" -> ":feature-two"
":app" -> ":feature-exclusion-test"
":app" -> ":lib"
":feature-one" -> ":core"
":feature-one" -> ":lib" [color=red style=bold]
":feature-one" -> ":feature-exclusion-test"
":lib" -> ":core" [color=red style=bold]
":feature-exclusion-test" -> ":core"
":feature-two" -> ":lib"
":feature-two" -> ":core"
}
```
<img width="394" alt="Screenshot 2020-05-11 at 22 40 58" src="https://user-images.githubusercontent.com/6277721/81609747-b52bff80-93d8-11ea-9cc0-d6e701f43ee2.png">

Please post gradle scripts of some `:b` and `:c` cases if the problem is there in your project or the expected output of `./gradlew app:generateModulesGraphvizText` to understand. Thank you

**Comment by ILikeYourHat** [comment] 2020-05-12 06:26
You are right, the problem is elsewhere, in my `gradle.properties` file, where I have this line:
`org.gradle.configureondemand=true`. It breaks plugin in the way I described. Accidentally copied this configuration to your example, sorry 😄 

Still, this shouldn't break the plugin.

**Comment by jraska** [comment] 2020-05-12 18:28
Well this one is a tricky one. At the same time it could be harmful that the plugin will trigger configuration of whole modules graph. I will have a look into it a bit more, but now I think the recommendation would be just run the assertions on your CI build where everything is configured, in case of generating the graph I would recommend `--no-configure-on-demand` flag.

**Comment by ILikeYourHat** [comment] 2020-05-13 10:30
Your approach with `--no-configure-on-demand` flag works for my case, thank you :)

**Comment by jraska** [comment] 2020-05-23 13:48
Added a note into Readme #57. I believe the plugin should not try to resolve it by itself, because we could start enumerating too many tasks causing pain to the users.

**Closed** 2020-05-23 13:48 UTC
