### ISSUE TITLE
Support for "TYPESAFE_PROJECT_ACCESSORS"

### ISSUE THREAD

**Issue by ILikeYourHat** [jraska/modules-graph-assert#113] opened 2021-08-15 14:40 UTC
Hi, Gradle in version 7.0 introduced a feature called [typesafe project accessors](https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors). Unfortunately, module dependencies declared this way are not visible in the generated project graph. This is an experimental feature, but it looks very promising and probably will be stable soon. Can you add support for it?

**Comment by jraska** [comment] 2021-08-17 21:22
Hey Marcin,

Thanks for raising this.

Not in near future as I don't want to depend on experimental API :) 

Anyway can you imagine how would look like the code adding the Type-safe project dependencies? The picking dependencies part is [here](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/assertion/GradleDependencyGraphFactory.kt#L25).

**Comment by eugene-krivobokov** [comment] 2021-10-06 08:50
> Not in near future as I don't want to depend on experimental API 

If I'm not mistaken the root cause is using a specific internal implementation `DefaultProjectDependency`.
It can be replaced by the public interface `ProjectDependency`. It covers the case with type-safe project accessors.
Type-safe project accessors dependency is another internal implementation of this interface.

**Comment by jraska** [comment] 2021-10-15 22:28
Resolved by [version 1.6.0](https://github.com/jraska/modules-graph-assert/releases/tag/1.6.0).

**Closed by jraska** 2021-10-15 22:28 UTC
